PLUGINS = [u"disqus_static"]

DISQUS_SITENAME = u'Hansun Lam'
DISQUS_SECRET_KEY = u'FtPozsuP5kL0xEuN21KzDdHH16bH96UgZRUZ5YKpGrhoMXmVC1Zb251ITBuLd1Ip'
DISQUS_PUBLIC_KEY = u'zgXzvEGytYqo0Q5lUIHQBYQL1U2gNehQrCwmiZNqxCEsnCBbClPmUO4xH5ntCFVt'